# Generated by Django 3.2 on 2022-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='月')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('category', models.CharField(choices=[('salary', '給料'), ('sideline', '副業')], max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='摘要')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='月')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('category', models.CharField(choices=[('Food expenses', '食費'), ('Utility bills', '水道光熱費'), ('Hobbies / Entertainment', '趣味・娯楽')], max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='摘要')),
            ],
        ),
    ]
